### ISSUE TITLE
I can jump off of spikes

### ISSUE THREAD

**Issue by JeffreyAngell** [colindt/unity-platformer#10]
This is easiest to show in the test level. Just go until almost the end, and try jumping off of the spikes.

**Comment by joe-eklund** [comment]
I think this has to do with the bug in the physics engine that Ben has mentioned. If you start the intro level and just spam jump while holding the left arrow key, your character can jump all the way to the top of the level. I believe this is the same bug.

So in your case, because of the position of gravity, you are actually jumping off the regular blocks, not the spikes.

Edit: Fixed a word.

**Comment by JeffreyAngell** [comment]
Possibly, but as a side note, at the beginning of the level you don't have
to hold the left key. You don't even have to go left at all.

**Comment by joe-eklund** [comment]
That is an excellent point. I'll have to look into it more to see exactly which object your character is jumping off of, if any. It could just be a bug in the jump code itself.

**Comment by joe-eklund** [comment]
I think it is because there is a message box there. Both the message box and spikes have "isTrigger" selected in their collider. That means that you can move through them, but your script can execute something when your character moves through it. 

I'm looking into a fix for it.

**Comment by JeffreyAngell** [comment]
It looks like you cannot jump off spikes in spiral spikes level, but I can try to verify that further.

**Comment by joe-eklund** [comment]
I'm almost positive it has to do with the Box Collider 2D. If you turn on the isTrigger option, then your character can do double/triple/seemingly infinite jumping while in the trigger box. If you cover the whole level in a Box Collider 2D and turn on the isTrigger, you have infinite jumping.

**Comment by zygoth** [comment]
Change the collider mask from default to Interactive Blocks, that will stop
you from jumping off it.

**Comment by joe-eklund** [comment]
Do you mean under the Sprite Renderer component and it's corresponding value titled "Sorting Layer?" Change that to be Interactive Blocks? I tried that and it didn't fix it. Where is the collider mask value?

**Comment by joe-eklund** [comment]
Ah I see now Ben. Disregard my previous comment.

**Comment by joe-eklund** [comment]
In https://github.com/colindt/unity-platformer/commit/7c0eb7830a5e1ce9891d57c32347bf2c1397ce22 I think I fixed the bug for infinite jumping based on Ben's fix.

**Comment by joe-eklund** [comment]
Closing issue as it has been fixed.
