### ISSUE TITLE
Health bar doesn't scale to the screen position based on your screen resolution.

### ISSUE THREAD

**Issue by joe-eklund** [colindt/unity-platformer#11]
Basically, the health bar needs to stay in the same position (bottom left corner) regardless of what resolution you play the game at.

**Comment by joe-eklund** [comment]
This should be fixed now with commit https://github.com/colindt/unity-platformer/commit/22f5443a1ecac0ab7d572c92e5afec0fc9c96e9e Report here if you still cannot see the health bar.

**Comment by JeffreyAngell** [comment]
For now, this is fixed.
