### ISSUE TITLE
In intro/test level, player can go backwards in the level and get stuck.

### ISSUE THREAD

**Issue by JeffreyAngell** [colindt/unity-platformer#13]

**Comment by colindt** [comment]
I know there were a bunch in the spiral spikes level (fixed by https://github.com/colindt/unity-platformer/commit/8948b71e9e06324e601fe339119517781416527a), but where were they in the intro level?

**Comment by JeffreyAngell** [comment]
It's the hit box on the gravity blocks that lets you do it. If we fix the hit box, it may not be possible anymore.

Also, it's still possible in spiral spikes at the beginning, but the spikes are a deterrent. Are we relying on the user not wanting to get hurt?
