### ISSUE TITLE
Halp! Everthing broke! (sprite scaling)

### ISSUE THREAD

**Issue by colindt** [colindt/unity-platformer#23]
Here's what the prototyping level looks like to me:
![Prototyping](https://cloud.githubusercontent.com/assets/5973692/6990067/eb51ac98-da21-11e4-86d3-cf26cd20c23e.png)

And here's spiral spikes:
![Spiral Spikes](https://cloud.githubusercontent.com/assets/5973692/6990068/eb594fde-da21-11e4-8768-50ad5fdd3d9e.png)

Yeah… I'm guessing it's related to https://github.com/colindt/unity-platformer/commit/c8beddb575a838dee9d4d96dab3b2c6063742ab8.

**Comment by zygoth** [comment]
You can fix this by resetting all the sprites "pixels to units" to 10.  I
have no idea how they all got changed to 16.  I've already worked on this
for 3 hours today so I can't fix it myself at the moment, but it's easy to
do.

**Comment by colindt** [comment]
It appears that something is forcing the sprites to be powers of two. I can't find any obvious reason for it. I found another sort of round about way of setting it to 10, and that fixes it in Prototyping, but not in the other scenes. Before c8beddb (I checked and that definitely was the commit that broke it) it was actually 100.

This is making less sense the more I study it. Can someone else who knows Unity better look into it?

**Comment by zygoth** [comment]
The asset that I downloaded for pixel perfect graphics was messing with
unity.  I commented out the offending line of code, you can change the
pixels per unit fine now.  BTW, scale needs to be at 1 for the game to work
on android, so go ahead and set pixels per unit to 10 and scale to 1 on
things if you can.  We really need to make a basic block prefab so we can
change everything at once easily.
