### ISSUE TITLE
Intro level camera is too wide

### ISSUE THREAD

**Issue by colindt** [colindt/unity-platformer#31]
The camera shows too much stuff:

![screenshot-131](https://cloud.githubusercontent.com/assets/5973692/7099708/d1623dd4-dfb7-11e4-9909-e1028fd43d6c.png)

I kind of figured that this was related to the pixel perfect or Android stuff and someone would be aware of it, but I thought I'd document it anyway.

**Comment by zygoth** [comment]
This is not a bug, export to windows or android and it will be fine.  It's
just the way the player window works in Unity.  You can resize it in Unity
if you want to only see what you should.
