### ISSUE TITLE
Character takes double damage when has half health sometimes.

### ISSUE THREAD

**Issue by joe-eklund** [colindt/unity-platformer#7]
Occasionally, the player will take double damage from a spike when at half health. They should enter the invulnerability phase, like the previous two hits from the spike. This seems happen much more often if you just sit in a spike. If you go into a spike and leave, wait for invulnerability to wear off, and then reenter the spike it usually functions correctly. I am unsure if this is related at all to the animation issue found here: https://github.com/colindt/unity-platformer/issues/6

**Comment by JeffreyAngell** [comment]
I've found that this seems to happen more often if I'm jumping when I hit the spikes.

**Comment by joe-eklund** [comment]
I think I fixed this and https://github.com/colindt/unity-platformer/issues/6 in my latest commit (https://github.com/colindt/unity-platformer/commit/6b2dd424e84c6386ef8278f9dbb5e551fcb7a017). I changed the timer to use invoke instead of the WaitForSeconds command. Need people to confirm this fix for me. Thanks.

**Comment by JeffreyAngell** [comment]
It seems to be working for me, but my concern is that I can't see my health bar.

**Comment by joe-eklund** [comment]
The new one? I changed it from the old one. It should be in the bottom left now.

**Comment by joe-eklund** [comment]
I think I need to change the canvas to scale with the screen resolution. I'll see if that works.

**Comment by zygoth** [comment]
nice job!

**Comment by joe-eklund** [comment]
Well I am going to close this issue because it seems fixed now and open up a different one for the one Jeff mentioned.

**Comment by joe-eklund** [comment]
Well I am going to close this issue because it seems fixed now and open up a different one for the one Jeff mentioned. If you ever come across it again, reopen it to let me know.
